### ISSUE TITLE
Foodmarket/Fusion

### ISSUE THREAD

**Issue by Straehlc** [famoser/Mensa#42] opened 2023-09-27 07:57 UTC
It seems that the app can't fetch the data of the foodmarket menu or fusion menu. 
The info is avaible on the websites.
I don't know if there are other mensa which don't work.
Untere Mensa and Rämi still function.
I use the newest version of the playstore on a Samsung S22.
Unfortunately I couldn't confirm if it is only at my end.
 Thank you for your work.

**Comment by jnzd** [comment] 2023-09-27 13:45
It's all the ETH mensas that are displayed as closed. UZH mensas are unaffected.

**Comment by famoser** [comment] 2023-09-27 20:29
The recently published update switches to a new API for ETH canteens (as the previous API unfortunately does not return menus for all Mensas anymore). 

I cannot reproduce the issues you are seeing; specifically the foodmarket / fusion meal works on my devices. Can you please try to refresh from within the app ("scroll up" in the overview until the loading symbol turns)? In any case, a screenshot would probably help.

I pushed out an update today, too; but this only improves the dark mode.

**Comment by jnzd** [comment] 2023-09-27 20:44
The issue is persistent for me. I refreshed multiple times, cleared the cache, deleted all app data, and I also uninstalled and reinstalled the app.
I'm running Android 12.

Here is a screenshot of how it looks for me
![image](https://github.com/famoser/Mensa/assets/26679346/f6061bd3-857b-4ce3-bc9e-f6629cae367e)

**Comment by famoser** [comment] 2023-09-28 06:18
I think I got it. Could it be that you are using an locale where the first day of the week is not a monday, but something else (e.g. a sunday)?

**Comment by jnzd** [comment] 2023-09-28 06:21
Yes! Thank you. I have set my phone to US English.

**Comment by famoser** [comment] 2023-09-28 06:24
If it is not too much trouble; could you please verify that if you set it to a locale with Monday as the first day of the week, it works as expected?

I will push out an update right now with this change in any case; just to be sure not to have missed anything else.

**Comment by jnzd** [comment] 2023-09-28 06:29
Sure. Just set it to German and it works as expected.
![Screenshot_20230928_082704_Mensa.jpg](https://github.com/famoser/Mensa/assets/26679346/b5cb0a3d-99b8-48ec-9fcb-40d0335a8c1f)

**Comment by famoser** [comment] 2023-09-28 06:32
Nice. Thank you!

The release has been sent to review; now it is up to google to review it. I will keep this issue open until then, so others easily find the discussion.

**Comment by Straehlc** [comment] 2023-09-28 06:38
Heya,
Thank you both.
I installed the new apk from git.
It seems to work now.

**Comment by famoser** [comment] 2023-09-28 12:50
Update is published, so I am closing the issue now.

I believe the fundamental issue to be resolved (no ETH canteens shown at all). 

The other reported issue (foodmarket empty), for which I got another independent report, is likely a consequence, but hard to reconstruct due to the various levels of caching used by the app. The issue disappears if the app is reinstalled. I believe the issue to disappear completely after one day of using the update, as any canteen-level caching is respective to a day.

**Closed by famoser** 2023-09-28 12:50 UTC
Labels: bug
